services:
  db:
    image: postgres:15-alpine  
    container_name: blog_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: blog_app
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SQLALCHEMY_TRACK_MODIFICATIONS: ${SQLALCHEMY_TRACK_MODIFICATIONS}
    volumes:
      - .:/app  # Mount local directory to container

volumes:
  pgdata:
